--INSERT INTO table_name (column_list)
--VALUES( value_list);

--First, specify the name of the table into which you want to insert.
--Second, specify a list of comma-separated column names within parentheses.
--Third, specify a list of comma-separated values that corresponds to the column list.

create table discounts(
    discount_id number generated by default as identity,
    discount_name VARCHAR2(255) not null,
    amount number (3,1) not null,
    start_date date not null,
    expired_date date not null
    );
    
insert into discounts (discount_name,amount,start_date,expired_date)
values('Summer Promotion', 9.5, DATE '2017-05-01', Date '2017-08-31');

select
    *
from 
    discounts;
insert into discounts(discount_name, amount, start_date, expired_date)
values('Winter Promotion', 10.5, Current_date, date '2017-12-31');
